#include<iostream>
using namespace std;
struct book
{
char title[50];
char author_name[30];
int no_pages;
float price;
char edition[50];
};
int main()
{
book b1,b2,b3,b4,b5;
cout<<"-----Enter First book detail-----"<<endl;
cout<<"\nEnter the tile of book: ";
cin.get(b1.title,50);
cout<<"Enter the author name: ";
cin>>b1.author_name;
cout<<"Enter the no of pages: ";
cin>>b1.no_pages;
cout<<"Enter the price of book: ";
cin>>b1.price;
cout<<"Enter the edition: ";
cin>>b1.edition;
cin.ignore();
cout<<"-----Enter 2nd book detail-----"<<endl;
cout<<"\nEnter the tile of book: ";
cin.get(b2.title,50);
cout<<"Enter the author name: ";
cin>>b2.author_name;
cout<<"Enter the no of pages: ";
cin>>b2.no_pages;
cout<<"Enter the price of book: ";
cin>>b2.price;
cout<<"Enter the edition: ";
cin>>b2.edition;
cin.ignore();
cout<<"-----Enter 3rd book detail-----"<<endl;
cout<<"\nEnter the tile of book: ";
cin.get(b3.title,50);
cout<<"Enter the author name: ";
cin>>b3.author_name;
cout<<"Enter the no of pages: ";
cin>>b3.no_pages;
cout<<"Enter the price of book: ";
cin>>b3.price;
cout<<"Enter the edition: ";
cin>>b3.edition;
cin.ignore();
cout<<"-----Enter 4th book detail-----"<<endl;
cout<<"\nEnter the tile of book: ";
cin.get(b4.title,50);
cout<<"Enter the author name: ";
cin>>b4.author_name;
cout<<"Enter the no of pages: ";
cin>>b4.no_pages;
cout<<"Enter the price of book: ";
cin>>b4.price;
cout<<"Enter the edition: ";
cin>>b4.edition;
cin.ignore();
cout<<"-----Enter 5th book detail-----"<<endl;
cout<<"\nEnter the tile of book: ";
cin.get(b5.title,50);
cout<<"Enter the author name: ";
cin>>b5.author_name;
cout<<"Enter the no of pages: ";
cin>>b5.no_pages;
cout<<"Enter the price of book: ";
cin>>b5.price;
cout<<"Enter the edition: ";
cin>>b5.edition;
cout<<"----First book detail-----"<<endl;
cout<<"\nTitle of the book: "<<b1.title<<endl;
cout<<"Author name: "<<b1.author_name<<endl;
cout<<"Price of book: "<<b1.price<<endl;
cout<<"Edition of the book: "<<b1.edition<<endl;
cout<<"----Second book detail-----"<<endl;
cout<<"\nTitle of the book: "<<b2.title<<endl;
cout<<"Author name: "<<b2.author_name<<endl;
cout<<"Price of book: "<<b2.price<<endl;
cout<<"Edition of the book: "<<b2.edition<<endl;
cout<<"----Third book detail-----"<<endl;
cout<<"\nTitle of the book: "<<b3.title<<endl;
cout<<"Author name: "<<b3.author_name<<endl;
cout<<"Price of book: "<<b3.price<<endl;
cout<<"Edition of the book: "<<b3.edition<<endl;
cout<<"----Fourth book detail-----"<<endl;
cout<<"\nTitle of the book: "<<b4.title<<endl;
cout<<"Author name: "<<b4.author_name<<endl;
cout<<"Price of book: "<<b4.price<<endl;
cout<<"Edition of the book: "<<b4.edition<<endl;
cout<<"----Fifth book detail-----"<<endl;
cout<<"\nTitle of the book: "<<b5.title<<endl;
cout<<"Author name: "<<b5.author_name<<endl;
cout<<"Price of book: "<<b5.price<<endl;
cout<<"Edition of the book: "<<b5.edition<<endl;
return 0;
}
